name: "JCSS"
code_location: "https://github.com/imorourke/portsmouthracecalc/"
disclaimer: "All race results are unofficial. Official results placements are determined by club officers at the end of seach series."
fleets:
  portsmouth_2017:
    portsmouth_table: fleets/portsmouth_table_2017.csv
    source: https://www.ussailing.org/wp-content/uploads/2018/01/2017-Portsmouth-Precalculated-Classes.pdf
    wind_map:
      default_index: 0
      map_values:
        - start_bf: 0
          end_bf: 1
          index: 1
        - start_bf: 2
          end_bf: 3
          index: 2
        - start_bf: 4
          end_bf: 4
          index: 3
        - start_bf: 5
          end_bf: 9
          index: 4
series:
  2016_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2016/s1.yaml
  2016_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2016/s2.yaml
  2016_series_3:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2016/s3.yaml
  2017_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2017/s1.yaml
  2017_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2017/s2.yaml
  2017_series_3:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2017/s3.yaml
  2018_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2018/s1.yaml
  2018_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2018/s2.yaml
  2018_series_3:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2018/s3.yaml
  2019_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2019/s1.yaml
  2019_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2019/s1.yaml
  2019_series_3:
    fleet: portsmouth_2017
    valid_required_skippers: 3
    race_file: 2019/s3.yaml
  2020_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2020/s1.yaml
  2020_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2020/s1.yaml
  2021_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2021/s1.yaml
  2021_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2021/s1.yaml
  2022_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2022/s1.yaml
  2022_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2022/s1.yaml
  2022_series_3:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2022/s3.yaml
  2023_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2023/s1.yaml
  2023_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2023/s2.yaml
  2024_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2024/s1.yaml
  2024_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2024/s2.yaml
  2024_series_3:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2024/s3.yaml
  2025_series_1:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2025/s1.yaml
  2025_series_2:
    fleet: portsmouth_2017
    valid_required_skippers: 4
    race_file: 2025/s2.yaml
